name: Convert to PDF

on:
push:
  branches: ["master"]

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    container:
      image: docker://pandoc/latex:latest
      options: --entrypoint=sh

    steps:
    - uses: actions/checkout@v3
    - name: Prepare output directories
      run: |
        for d in */; do
          mkdir -p output/$d
        done
    - name: Convert md to pdf
      run: |
        find ./ -iname "*.md" -type f -exec sh -c "pandoc ${0} -o output/${0%.md}.pdf" {} \;
    - uses: actions/upload-artifact@master
      with:
        name: output
        path: output