name: Convert to PDF

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare output directories
        run: |
          for d in */; do
            mkdir -p output/$d
          done
      - name: convert md to docx
        uses: docker://pandoc/latex:latest
        with:
          entrypoint: /bin/sh
          args: -c "for f in */*.md; do pandoc $f -s -o ${f%.md}.pdf; done"
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
